// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel PhotonRay
#pragma kernel ScreenRay


struct Ray 
{
    float3 origin;
    float3 dir;
};

struct Triangle
{
    float3 v0, v1, v2;
    float3 normal;
    float2 uv0, uv1, uv2;
};

struct Photon
{
    int strength;
    float3 direction;
    float2 px, py;
};


RWTexture2D<int> PhotonCount;
RWTexture2D<float4> Result;
RWTexture2D<float4> Result2;
RWStructuredBuffer<Photon> Photons;

StructuredBuffer<Triangle> GroundTriangles;
StructuredBuffer<Triangle> WaterTriangles;


int GroundTriangleCount;
int WaterTriangleCount;

float3 LightPosition;
int TextureWidth;
int TextureHeight;
float eta1;
float eta2;
int GatheringRadius;

float3 CameraPosition;
float3 CameraForward;
float3 CameraUp;
float3 CameraRight;
float CameraFOV;

int photonsSize;


//Photon[,] photonMatrix;




// Returns hit point on ray (t) and hit point on triangle in barycentric coordinates (u, v, (1-u-v))
// taken from https://en.wikipedia.org/wiki/M%C3%B6ller%E2%80%93Trumbore_intersection_algorithm
bool ray_intersects_triangle(Ray ray, Triangle tri, out float time, out float u_out, out float v_out)
{
    time = 0; u_out = 0; v_out = 0; 
    float3 ray_dir = ray.dir;
    float3 ray_origin = ray.origin;
    float epsilon = 1e-6;

    float3 edge1 = tri.v1 - tri.v0;
    float3 edge2 = tri.v2 - tri.v0;

    // Backface culling, assuming CCW-wound triangles.
    /*float3 normal = cross(edge1, edge2); // No need to normalize
	if (dot(normal, ray_dir) > 0) return false; */

    float3 ray_cross_e2 = cross(ray_dir, edge2);
    float det = dot(edge1, ray_cross_e2);

    if (abs(det) < epsilon) return false; // Ray is parallel to triangle

    float inv_det = 1.0 / det;
    float3 s = ray_origin - tri.v0;
    float u = inv_det * dot(s, ray_cross_e2);

    if (u < -epsilon || u - 1 > epsilon) return false; // Ray passes outside edge2's bounds

    float3 s_cross_e1 = cross(s, edge1);
    float v = inv_det * dot(ray_dir, s_cross_e1);

    if (v < -epsilon || u + v - 1 > epsilon) return false; // Ray passes outside edge1's bounds

    // The ray line intersects with the triangle.
    // We compute t to find where on the ray the intersection is.
    float t = inv_det * dot(edge2, s_cross_e1);
    if (t > epsilon)
    {
        time = t;
        u_out = u;
        v_out = v;
        return true;
    }
    return false;
}

/* float GatherPhotons(float2 centerPixel, float radiusPixels)
{
    float3 total = float3(0,0,0);
    if (radiusPixels == 0) {return PhotonCount[centerPixel];}
    
    // Get all pixels within a square
    for (int dx = -radiusPixels; dx <= radiusPixels; dx++)
    {
        for (int dy = -radiusPixels; dy <= radiusPixels; dy++)
        {
            // Check if in circle
            if (dx*dx + dy*dy <= radiusPixels*radiusPixels)
            {
                int2 coord = 
                clamp(
                    centerPixel + int2(dx, dy), 
                    int2(0,0), 
                    int2(TextureWidth-1, TextureHeight-1)
                );
                total += PhotonCount[coord];
            }
        }
    }
    
    float area = 3.14159 * radiusPixels * radiusPixels;
    return total / area;
} */


float3 GatherPhotonsDir(float2 centerPixel, float radiusPixels)
{
    float3 total = float3(0,0,0);
    if (radiusPixels == 0) 
    {
        int index = centerPixel.y * TextureWidth + centerPixel.x;
        return (Photons[index].strength * float3(1, 1, 1)) * Photons[index].direction;
    }
    
    // Get all pixels within a square
    for (int dx = -radiusPixels; dx <= radiusPixels; dx++)
    {
        for (int dy = -radiusPixels; dy <= radiusPixels; dy++)
        {
            // Check if in circle
            if (dx*dx + dy*dy <= radiusPixels*radiusPixels)
            {
                int2 coord = 
                clamp(
                    centerPixel + int2(dx, dy), 
                    int2(0,0), 
                    int2(TextureWidth-1, TextureHeight-1)
                );
                int index = coord.y * TextureWidth + coord.x;
                float3 phi = Photons[index].strength * float3(1, 1, 1);
                float cos_theta = Photons[index].direction;
                total += phi * cos_theta;
            }
        }
    }
    
    float area = 3.14159 * radiusPixels * radiusPixels;
    return total / area;
}

float3 GatherPhotonsGaussian(float2 centerPixel, float radiusPixels)
{
    float alpha = 0.918;
    float beta = 1.953;
    float e =  2.718281828459045235360287471;

    float3 total = float3(0,0,0);
    if (radiusPixels == 0) 
    {
        int index = centerPixel.y * TextureWidth + centerPixel.x;
        return (Photons[index].strength * float3(1, 1, 1)) * Photons[index].direction;
    }
    
    // Get all pixels within a square
    for (int dx = -radiusPixels; dx <= radiusPixels; dx++)
    {
        for (int dy = -radiusPixels; dy <= radiusPixels; dy++)
        {
            // Check if in circle
            if (dx*dx + dy*dy <= radiusPixels*radiusPixels)
            {
                int2 coord = 
                clamp(
                    centerPixel + int2(dx, dy), 
                    int2(0,0), 
                    int2(TextureWidth-1, TextureHeight-1)
                );
                int index = coord.y * TextureWidth + coord.x;

                float distSqared = pow(centerPixel.x - coord.x, 2) + pow(centerPixel.y - coord.y, 2);
                float term = (1 - pow(e, (-beta * distSqared/(2*pow(radiusPixels,2))))) / (1- pow(e,-beta));
                float weight = alpha * (1 - term);

                float3 phi = Photons[index].strength * float3(1, 1, 1);
                float cos_theta = Photons[index].direction;
                total += phi * cos_theta * weight;
            }
        }
    }
    
    float area = 3.14159 * radiusPixels * radiusPixels;
    return total / area;
}

bool CheckWaterHit(inout Ray ray)
{
    bool hit_water = false;
    
    // Check if the light intersects the water surface
    for (int i = 0; i < WaterTriangleCount; i++)
    {
        float t, bu, bv;
        Triangle curr_tri = WaterTriangles[i];
        if (ray_intersects_triangle(ray, curr_tri, t, bu, bv))
        {
            hit_water = true;

            // Calculate end points and direction for the ray
            float3 hit_normal = normalize(curr_tri.normal);
            float3 hit_point = (1-bu-bv)* curr_tri.v0 + bu* curr_tri.v1 + bv* curr_tri.v2;

            float3 e = normalize(hit_point - ray.origin);

            float eta_rel = eta1/eta2;
            float mult = dot(e, hit_normal);
            float under_sqrt = 1 + pow(eta_rel, 2) * (pow(mult, 2)-1);

            float3 new_dir = hit_normal * (eta_rel* mult - sqrt(1+pow(eta_rel, 2) * (pow(mult, 2) - 1))) + eta_rel*e;

            // Update ray position and direction
            ray.origin = hit_point;
            ray.dir = new_dir;
            break;

        }
    } 
    return hit_water;
}


void CheckGroundHit(inout Ray ray, inout int hit_index, inout float hit_u, inout float hit_v)
{
    float closest = 1e9;
    // Check if the light intersects the box
    for (int j = 0; j < GroundTriangleCount; j++) 
    {
        float t, bu, bv;
        if (ray_intersects_triangle(ray, GroundTriangles[j], t, bu, bv))
        {
            if (t < closest)
            {
                closest = t;
                hit_index = j;
                hit_u = bu;
                hit_v = bv;
            }
        }
    }
}


[numthreads(8,8,1)]
void PhotonRay (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint) TextureWidth || id.y >= (uint) TextureHeight) {return;} 


    float u = id.x / (float)TextureWidth;
    float v = id.y / (float)TextureHeight;

    Ray ray;
    ray.origin = LightPosition;
    ray.dir = normalize(float3((u - 0.5), -1, (v - 0.5)));  // Create cone of light

    bool hit_water = CheckWaterHit(ray);
    while (hit_water) {
        hit_water = CheckWaterHit(ray);
    }

    // TODO: Monte Carlo for each hit, probabilities depend on material??

    int hit_index = -1;
    float hit_u = 0, hit_v = 0;

    CheckGroundHit(ray, hit_index, hit_u, hit_v);

    // If no ground is hit, ignore
    if (hit_index < 0) {
        return;
    }

    // Translate from barycentric to UV coordinate
    Triangle hit_tri = GroundTriangles[hit_index];
    float2 hit_uv = (1-hit_u-hit_v)* hit_tri.uv0 + hit_u* hit_tri.uv1 + hit_v* hit_tri.uv2;


    uint2 tex_coord = uint2(hit_uv.x * TextureWidth, hit_uv.y * TextureHeight);
    tex_coord.x = clamp(tex_coord.x, 0, TextureWidth-1);
    tex_coord.y = clamp(tex_coord.y, 0, TextureHeight-1);


    uint index = tex_coord.y * TextureWidth + tex_coord.x;
    Photons[index].strength += 1;
    Photons[index].direction = abs(dot(ray.dir, hit_tri.normal));
    Photons[index].px = id.x;
    Photons[index].py = id.y;

    // Update texture with light
    PhotonCount[tex_coord] += 1;
}



[numthreads(8,8,1)]
void ScreenRay (uint3 id : SV_DispatchThreadID)
{
    float aspect = TextureWidth / (float) TextureHeight;
    float scale = tan(CameraFOV * 0.5 * 3.14159 / 180.0);

    float2 uv = float2(id.x / (float) TextureWidth, id.y / (float) TextureHeight);
    float2 ndc = float2((uv.x * 2.0 - 1.0) * aspect * scale, (uv.y * 2.0 - 1.0) * scale);

    Ray ray;
    ray.origin = CameraPosition;
    ray.dir = normalize(CameraForward + CameraRight * ndc.x + CameraUp * ndc.y);


    float closest = 1e9;
    int hit_index = -1;
    float hit_u = 0, hit_v = 0;

    // Check if the light intersects the box
    for (int j = 0; j < GroundTriangleCount; j++) 
    {
        float t, bu, bv;
        if (ray_intersects_triangle(ray, GroundTriangles[j], t, bu, bv))
        {
            if (t < closest)
            {
                closest = t;
                hit_index = j;
                hit_u = bu;
                hit_v = bv;
            }
        }
    }
    // If no ground is hit, continue
    if (hit_index < 0) {
        return;
    }

    // Translate from barycentric to texture coordinate
    Triangle hit_tri = GroundTriangles[hit_index];
    float2 hit_uv = (1-hit_u-hit_v)* hit_tri.uv0 + hit_u* hit_tri.uv1 + hit_v* hit_tri.uv2;

    uint2 tex_coord = uint2(hit_uv.x * TextureWidth, hit_uv.y * TextureHeight);
    tex_coord.x = clamp(tex_coord.x, 0, TextureWidth-1);
    tex_coord.y = clamp(tex_coord.y, 0, TextureHeight-1);

    // Gather photons
    uint numPhotons = PhotonCount[tex_coord];
    //float raw = GatherPhotons((int2)tex_coord, GatheringRadius);
    float3 raw = GatherPhotonsGaussian((int2)tex_coord, GatheringRadius);       // TODO:Change this line to change method
    float3 brightness = raw/20.0; // Extra normalisation

    // Update texture with light
    Result[id.xy] = float4(brightness, 1);  // Graphics
    Result2[tex_coord] = float4(brightness, 1);     // Texture painting
}



