/* // Each #kernel tells which function to compile; you can have many kernels


struct Ray 
{
    float3 origin;
    float3 dir;
};

struct Triangle
{
    float3 v0, v1, v2;
    float3 normal;
    float2 uv0, uv1, uv2;
};

// Create a RenderTexture with enableRandomWrite flag and set it
// with cs.SetTexture
RWTexture2D<uint> PhotonCount;
RWTexture2D<float4> Result;

StructuredBuffer<Triangle> GroundTriangles;
int GroundTriangleCount;

int TextureWidth;
int TextureHeight;

float3 CameraPosition;
float3 CameraForward;
float3 CameraUp;
float3 CameraRight;
float CameraFOV;

// Returns hit point on ray (t) and hit point on triangle in barycentric coordinates (u, v, (1-u-v))
// taken from https://en.wikipedia.org/wiki/M%C3%B6ller%E2%80%93Trumbore_intersection_algorithm
bool ray_intersects_triangle(Ray ray, Triangle tri, out float time, out float u_out, out float v_out)
{
    time = 0; u_out = 0; v_out = 0; 
    float3 ray_dir = ray.dir;
    float3 ray_origin = ray.origin;
    float epsilon = 1e-6;

    float3 edge1 = tri.v1 - tri.v0;
    float3 edge2 = tri.v2 - tri.v0;

    float3 ray_cross_e2 = cross(ray_dir, edge2);
    float det = dot(edge1, ray_cross_e2);

    if (abs(det) < epsilon) return false; // Ray is parallel to triangle

    float inv_det = 1.0 / det;
    float3 s = ray_origin - tri.v0;
    float u = inv_det * dot(s, ray_cross_e2);

    if (u < -epsilon || u - 1 > epsilon) return false; // Ray passes outside edge2's bounds

    float3 s_cross_e1 = cross(s, edge1);
    float v = inv_det * dot(ray_dir, s_cross_e1);

    if (v < -epsilon || u + v - 1 > epsilon) return false; // Ray passes outside edge1's bounds

    // The ray line intersects with the triangle.
    // We compute t to find where on the ray the intersection is.
    float t = inv_det * dot(edge2, s_cross_e1);

    if (t > epsilon)
    {
        time = t;
        u_out = u;
        v_out = v;
        return true;
    }
    return false;
}



[numthreads(8,8,1)]
void ScreenRay (uint3 id : SV_DispatchThreadID)
{
    float aspect = TextureWidth / (float) TextureHeight;
    float scale = tan(CameraFOV * 0.5 * 3.14159 / 180.0);

    float2 uv = float2(id.x / (float) TextureWidth, id.y / (float) TextureHeight);
    float2 ndc = float2((uv.x * 2.0 - 1.0) * aspect * scale, (uv.y * 2.0 - 1.0) * scale);

    Ray ray;
    ray.origin = CameraPosition;
    ray.dir = normalize(CameraForward + CameraRight * ndc.x + CameraUp * ndc.y);


    float closest = 1e9;
    int hit_index = -1;
    float hit_u = 0, hit_v = 0;

    // Check if the light intersects the box
    for (int j = 0; j < GroundTriangleCount; j++) 
    {
        float t, bu, bv;
        if (ray_intersects_triangle(ray, GroundTriangles[j], t, bu, bv))
        {
            if (t < closest)
            {
                closest = t;
                hit_index = j;
                hit_u = bu;
                hit_v = bv;
            }
        }
    }
    // If no ground is hit, continue
    if (hit_index < 0) {
        return;
    }

    // Translate from barycentric to UV coordinate
    Triangle hit_tri = GroundTriangles[hit_index];
    float2 hit_uv = (1-hit_u-hit_v)* hit_tri.uv0 + hit_u* hit_tri.uv1 + hit_v* hit_tri.uv2;


    uint2 tex_coord = uint2(hit_uv.x * TextureWidth, hit_uv.y * TextureHeight);
    tex_coord.x = clamp(tex_coord.x, 0, TextureWidth-1);
    tex_coord.y = clamp(tex_coord.y, 0, TextureHeight-1);

    uint numPhotons = PhotonCount[tex_coord];
    // Update texture with light
    Result[id.xy] = float4(0.1 * numPhotons, 0.1 * numPhotons, 0.1 * numPhotons, 1);

} */